# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import facenet_pb2 as facenet__pb2


class GetEmbeddingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/deploy.grpcserver.facenet.GetEmbedding/Get',
        request_serializer=facenet__pb2.ImageMessage.SerializeToString,
        response_deserializer=facenet__pb2.EmbeddingMessage.FromString,
        )


class GetEmbeddingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetEmbeddingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=facenet__pb2.ImageMessage.FromString,
          response_serializer=facenet__pb2.EmbeddingMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'deploy.grpcserver.facenet.GetEmbedding', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
