# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mtcnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mtcnn.proto',
  package='deploy.mtcngrpcserver.mtcnn',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmtcnn.proto\x12\x1b\x64\x65ploy.mtcngrpcserver.mtcnn\" \n\x0cImageMessage\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\x0c\"\x8a\x01\n\x0b\x46\x61\x63\x65Message\x12<\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32-.deploy.mtcngrpcserver.mtcnn.FaceMessage.Face\x1a=\n\x04\x46\x61\x63\x65\x12\x0c\n\x04\x62\x62ox\x18\x01 \x03(\x05\x12\x11\n\timage_dim\x18\x02 \x03(\x05\x12\x14\n\x0c\x61liged_image\x18\x03 \x01(\x0c\x32g\n\x07GetFace\x12\\\n\x03Get\x12).deploy.mtcngrpcserver.mtcnn.ImageMessage\x1a(.deploy.mtcngrpcserver.mtcnn.FaceMessage\"\x00\x62\x06proto3')
)




_IMAGEMESSAGE = _descriptor.Descriptor(
  name='ImageMessage',
  full_name='deploy.mtcngrpcserver.mtcnn.ImageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b64image', full_name='deploy.mtcngrpcserver.mtcnn.ImageMessage.b64image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=76,
)


_FACEMESSAGE_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage.Face.bbox', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_dim', full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage.Face.image_dim', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aliged_image', full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage.Face.aliged_image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=217,
)

_FACEMESSAGE = _descriptor.Descriptor(
  name='FaceMessage',
  full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='faces', full_name='deploy.mtcngrpcserver.mtcnn.FaceMessage.faces', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FACEMESSAGE_FACE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=217,
)

_FACEMESSAGE_FACE.containing_type = _FACEMESSAGE
_FACEMESSAGE.fields_by_name['faces'].message_type = _FACEMESSAGE_FACE
DESCRIPTOR.message_types_by_name['ImageMessage'] = _IMAGEMESSAGE
DESCRIPTOR.message_types_by_name['FaceMessage'] = _FACEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMessage = _reflection.GeneratedProtocolMessageType('ImageMessage', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMESSAGE,
  __module__ = 'mtcnn_pb2'
  # @@protoc_insertion_point(class_scope:deploy.mtcngrpcserver.mtcnn.ImageMessage)
  ))
_sym_db.RegisterMessage(ImageMessage)

FaceMessage = _reflection.GeneratedProtocolMessageType('FaceMessage', (_message.Message,), dict(

  Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), dict(
    DESCRIPTOR = _FACEMESSAGE_FACE,
    __module__ = 'mtcnn_pb2'
    # @@protoc_insertion_point(class_scope:deploy.mtcngrpcserver.mtcnn.FaceMessage.Face)
    ))
  ,
  DESCRIPTOR = _FACEMESSAGE,
  __module__ = 'mtcnn_pb2'
  # @@protoc_insertion_point(class_scope:deploy.mtcngrpcserver.mtcnn.FaceMessage)
  ))
_sym_db.RegisterMessage(FaceMessage)
_sym_db.RegisterMessage(FaceMessage.Face)



_GETFACE = _descriptor.ServiceDescriptor(
  name='GetFace',
  full_name='deploy.mtcngrpcserver.mtcnn.GetFace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=219,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='deploy.mtcngrpcserver.mtcnn.GetFace.Get',
    index=0,
    containing_service=None,
    input_type=_IMAGEMESSAGE,
    output_type=_FACEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETFACE)

DESCRIPTOR.services_by_name['GetFace'] = _GETFACE

# @@protoc_insertion_point(module_scope)
