# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mtcnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mtcnn.proto',
  package='image',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bmtcnn.proto\x12\x05image\" \n\x0cImageMessage\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\x0c\"1\n\x0b\x46\x61\x63\x65Message\x12\x0c\n\x04\x62\x62ox\x18\x01 \x01(\x0c\x12\x14\n\x0c\x61liged_image\x18\x02 \x01(\x0c\x32;\n\x07GetFace\x12\x30\n\x03Get\x12\x13.image.ImageMessage\x1a\x12.image.FaceMessage\"\x00\x62\x06proto3')
)




_IMAGEMESSAGE = _descriptor.Descriptor(
  name='ImageMessage',
  full_name='image.ImageMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b64image', full_name='image.ImageMessage.b64image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=54,
)


_FACEMESSAGE = _descriptor.Descriptor(
  name='FaceMessage',
  full_name='image.FaceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bbox', full_name='image.FaceMessage.bbox', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='aliged_image', full_name='image.FaceMessage.aliged_image', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=105,
)

DESCRIPTOR.message_types_by_name['ImageMessage'] = _IMAGEMESSAGE
DESCRIPTOR.message_types_by_name['FaceMessage'] = _FACEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageMessage = _reflection.GeneratedProtocolMessageType('ImageMessage', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEMESSAGE,
  __module__ = 'mtcnn_pb2'
  # @@protoc_insertion_point(class_scope:image.ImageMessage)
  ))
_sym_db.RegisterMessage(ImageMessage)

FaceMessage = _reflection.GeneratedProtocolMessageType('FaceMessage', (_message.Message,), dict(
  DESCRIPTOR = _FACEMESSAGE,
  __module__ = 'mtcnn_pb2'
  # @@protoc_insertion_point(class_scope:image.FaceMessage)
  ))
_sym_db.RegisterMessage(FaceMessage)



_GETFACE = _descriptor.ServiceDescriptor(
  name='GetFace',
  full_name='image.GetFace',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=107,
  serialized_end=166,
  methods=[
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='image.GetFace.Get',
    index=0,
    containing_service=None,
    input_type=_IMAGEMESSAGE,
    output_type=_FACEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETFACE)

DESCRIPTOR.services_by_name['GetFace'] = _GETFACE

# @@protoc_insertion_point(module_scope)
