# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mtcnn_pb2 as mtcnn__pb2


class GetFaceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/image.GetFace/Get',
        request_serializer=mtcnn__pb2.ImageMessage.SerializeToString,
        response_deserializer=mtcnn__pb2.FaceMessage.FromString,
        )


class GetFaceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GetFaceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=mtcnn__pb2.ImageMessage.FromString,
          response_serializer=mtcnn__pb2.FaceMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'image.GetFace', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
